# serverless.yml

service: hello-world-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  memorySize: 128
  timemout: 10

custom:
  functionsBasePath: src/handlers

functions:
  hello:
    handler: users.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-functions-base-path
